server:
  port: 8080

device:
  api:
    serverRoot: ${resource.gateway.tokenServer.baseUri}

management:
  context-path: /actuator

  # TODO OAUTH-3495 remove again
  endpoints:
    web:
      exposure:
        include: health,env,info
