server:
  port: 8080

device:
  api:
    serverRoot: ${resource.gateway.tokenServer.baseUri}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  server:
    base-path: /actuator
