server:
  port: 9999

resource:
  gateway:
    tokenServer:
      baseUri: http://localhost:7878/oauth

      clientId: validate
      clientSecret: the token

device:
  api:
    username: username
    password: password
